core/app/urls.py
from django.urls import path
from allauth.account.views import LoginView, LogoutView, SignupView
from .views import Index, UserUpdate
from .forms import UserCreateForm

app_name = 'app'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path("register/", SignupView.as_view(template_name="user_create_update.html", form_class=UserCreateForm), name="register"),
    path("user_update/<int:pk>/", UserUpdate.as_view(), name="user_update"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls'))
]

core/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    """
    Расширяем модель пользователя для добавления дополнительной информации,
    фактически создаем объект SocialAccount allauth с дополнительной информацией.
    """
    extra_data = models.CharField('Дополнительные данные в расширенной модели', max_length=512)
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

core/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserCreateForm(UserCreationForm):
    """
    Форма для правильного отображения порядка выводимых полей
    extra_data должно быть снизу, после обязательных полей
    """
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput)
    extra_data = forms.CharField(label="Дополнительные данные в расширенной модели", widget=forms.Textarea, required=False)
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "extra_data")


class UserUpdateForm(forms.ModelForm):
    """
    Форма изменения логина и дополнительной информации пользователя
    """
    extra_data = forms.CharField(label="Дополнительные данные в расширенной модели", widget=forms.Textarea, required=False)
    class Meta:
        model = User
        fields = ("username", "extra_data")

core/app/views.py
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserUpdateForm
from .models import User


class Index(TemplateView):
    """
    Главная страница, отображает текущего пользователя и его сохраненную дополнительную информацию
    """
    template_name = 'index.html'


class UserUpdate(LoginRequiredMixin, UpdateView):
    """
    Контроллер изменения имени и дополнительных данных пользователя
    """
    template_name="user_create_update.html"
    model=User
    form_class=UserUpdateForm
    success_url=reverse_lazy("app:index")
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Изменить данные пользователя"
        return context

core/app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css'%}">
    <title>D7.8 Домашнее задание</title>
</head>
<body class="text-secondary">
    <div class="container m-5 p-3 border border-info bg-light rounded">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

core/app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h2>Главная страница</h2>
    <p>Авторизация пользователя с использованием django-allauth и GitHub.</p>
    <br>
    <p>Пользователь: <span class="text-info"> {% if user.is_anonymous %} Не авторизован {% else %} {{ user }} {% endif %} </span></p>
    <p>Дополнительные данные пользователя: <span class="text-info">{% if user.extra_data %} {{ user.extra_data }} {% else %} нет {% endif %}</span></p>
    <div class="d-flex justify-content-between mt-5">
        <div>
            {% if user.is_anonymous %}
                <a class="btn btn-outline-info text-secondary" href="{% url 'app:register' %}">Регистрация</a>
                <a class="btn btn-outline-info text-secondary mx-3" href="{% url 'app:login' %}">Авторизация</a>
            {% else %}
                <a class="btn btn-outline-info text-secondary" href="{% url 'app:user_update' user.id %}">Изменить дополнительные данные пользователя</a>
                <a class="btn btn-outline-info text-secondary mx-3" href="{% url 'app:logout' %}">Выход</a>
            {% endif %}
        </div>
        <a class="btn btn-outline-info text-secondary" href="/admin">Admin</a>
    </div>

{% endblock %}

core/app/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Авторизация</h2>
    <form method="post">  
        {% csrf_token %}  
        {{ form|crispy }}  
        <div class="d-flex justify-content-between mt-5">
            <div>
                <input class="btn btn-outline-info text-secondary" type="submit" value="Вход">
                <a href="{% url 'app:index' %}" class="btn btn-outline-info text-secondary mx-3">Отмена</a>
            </div>
            <a href="/accounts/github/login" class="btn btn-success">Авторизация через GitHub</a>
        </div>

    </form>  
{% endblock %}

core/app/templates/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>Выход</h2>
    <p>Вы уверены, что хотите выйти?</p>
    <form action="/accounts/logout/" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-info text-secondary mt-5">Выйти</button>
        <a href="{% url 'app:index' %}" class="btn btn-outline-info text-secondary mt-5 mx-3">Вернуться</a>
    </form>
{% endblock %}

core/app/templates/user_create_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if title %}
        <h2>{{ title }}</h2>
    {% else %}
        <h2>Регистрация</h2>
    {% endif %}
    <form method="post">  
        {% csrf_token %}  
        {{ form|crispy }}
        <input class="btn btn-outline-info text-secondary mt-5" type="submit" value="Сохранить">
        <a href="{% url 'app:index' %}" class="btn btn-outline-info text-secondary mt-5 mx-3">Отмена</a>
    </form>  
{% endblock %}